name: flutter_ffmpeg
description: Flutter plugin to run FFmpeg on mobile platforms. Supports iOS and Android.
version: 0.5.2
homepage: https://github.com/tanersener/flutter-ffmpeg

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.0.14
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.flutter.ffmpeg
        pluginClass: FlutterFFmpegPlugin
      ios:
        pluginClass: FlutterFFmpegPlugin
